### ISSUE TITLE
about decode size limit

### ISSUE THREAD

**Issue by amazingfate** [JeffyCN/libv4l-rkmpp#10]
There are two locations defining decoder size limit: [meson_options.txt](https://github.com/JeffyCN/libv4l-rkmpp/blob/master/meson_options.txt#L7) and [libv4l-rkmpp-dec.c](https://github.com/JeffyCN/libv4l-rkmpp/blob/master/src/libv4l-rkmpp-dec.c#L38). By default we use the values defined in meson.
But that is a global config overwriting all the decoders.
AV1 decoder on rk3588 supports 8K while the h264/h265 decoders support up to 4K. So why do we need global size limit defined in meson?

**Comment by JeffyCN** [comment]
for old chips, there're some customers want to set limits in build scripts and based on chips

**Comment by amazingfate** [comment]
Got it. So just configuring meson_options.txt to 8K dec limit should be enough for rk3588. `frmsize` defined in `libv4l-rkmpp-dec.c` confused me.
