### ISSUE TITLE
是否可以在Electron中使用vpu进行视频解码

### ISSUE THREAD

**Issue by iyangsheng** [JeffyCN/libv4l-rkmpp#13]
Electron是基于chromium的桌面端开发框架，Electron也支持给上游的chromium打补丁https://www.electronjs.org/zh/docs/latest/development/patches

**Comment by JeffyCN** [comment]
没有计划支持，理论上可行，有兴趣可以自行尝试移植和调试

**Comment by iyangsheng** [comment]
我用[chromium_95.0.4638]中的补丁(https://github.com/JeffyCN/meta-rockchip/tree/b840f4116f593c8ca04b9003476c78d674273044/dynamic-layers/recipes-browser/chromium/chromium_95.0.4638)编译了chromium_95.0.4638，通过查看chrome://gpu 显示已经开启视频硬件解码，但是不能播放视频，启动命令
`chromium-browser --no-sandbox --gpu-sandbox-start-early --ignore-gpu-blacklist --ignore-gpu-blocklist --enable-accelerated-video-decode --enable-features=VaapiVideoDecoder`
![image](https://user-images.githubusercontent.com/39045336/221102127-c8295c1b-b0fc-42c3-a220-f8b9c1dcab7d.png)
![image](https://user-images.githubusercontent.com/39045336/221102157-d9becf62-00c4-4183-b75c-12a685773fa6.png)

控制台有报错

![image](https://user-images.githubusercontent.com/39045336/221102188-d29a0761-10c8-42bf-8dc5-e3ac73ac8778.png)

**Comment by JeffyCN** [comment]
--use-gl=egl

**Comment by iyangsheng** [comment]
还是不能播放

**Comment by JeffyCN** [comment]
此类功能依赖较多，请使用rockchip官方 buildroot/debian/yocto SDK

**Comment by JeffyCN** [comment]
基本流程是：
chromium检测/dev/video-dec0 /dev/video-enc0文件，然后调用libv4l-utils，触发里面的libv4l-rkmpp，然后走到rockchip mpp和mpp驱动去解码, 解码的图像通过egl导入纹理进行渲染
里面任何一个环节异常都会导致软解

总体流程比较复杂，如果不方便调试可以使用sdk调好的环境
创建虚拟设备节点:
```
                # Create dummy video node for V4L2 VDA/VEA with rkmpp plugin
                echo dec > /dev/video-dec0
                echo enc > /dev/video-enc0
```
