### ISSUE TITLE
video framerate is extramely low after commit f0d1d5364e30aa98f6d4cefd87f1e365ad5e205c

### ISSUE THREAD

**Issue by amazingfate** [JeffyCN/libv4l-rkmpp#19]
My environment: 
- rkr1 6.1 kernel
- chromium v121
- GPU driver is mainline panthor kernel driver and mainline git mesa
- Mesa has [patched gbm](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7745) to support NV12 rendering.
- mpp is from https://github.com/nyanmisaka/mpp/tree/jellyfin-mpp, from which https://github.com/nyanmisaka/mpp/commit/81aef472c2646878b65d901af5a83f4de73877df is necessary because kernel 6.1 has changed dma_heap. And  mpp also need hack from https://github.com/JeffyCN/libv4l-rkmpp/issues/12#issuecomment-1439445526 to support large av1 videos.

I encountered this issue before but at that moment I didn't configured all  things right. Now I find [this commit](https://github.com/JeffyCN/libv4l-rkmpp/commit/f0d1d5364e30aa98f6d4cefd87f1e365ad5e205c) has caused the low fps issue.

**Comment by JeffyCN** [comment]
could not reproduce this issue...

the only part of this commit that might affect the decoding flow is in rkmpp_dqbuf(), but it looks fine

**Comment by amazingfate** [comment]
Here are the logs with env `LIBV4L_RKMPP_LOG_LEVEL=7`
[rkmpp_fine.log.gz](https://github.com/JeffyCN/libv4l-rkmpp/files/15076584/rkmpp_fine.log.gz)
[rkmpp_slow.log.gz](https://github.com/JeffyCN/libv4l-rkmpp/files/15076586/rkmpp_slow.log.gz)

**Comment by amazingfate** [comment]
And a smaller patch to fix:
```
diff --git a/src/libv4l-rkmpp.c b/src/libv4l-rkmpp.c
index 7ad4b53..0179b92 100644
--- a/src/libv4l-rkmpp.c
+++ b/src/libv4l-rkmpp.c
@@ -669,6 +669,7 @@ int rkmpp_dqbuf(struct rkmpp_context *ctx, struct v4l2_buffer *buffer)

        pthread_mutex_lock(&queue->queue_mutex);
        rkmpp_buffer = TAILQ_FIRST(&queue->avail_buffers);
+       TAILQ_REMOVE(&queue->avail_buffers, rkmpp_buffer, entry);
        pthread_mutex_unlock(&queue->queue_mutex);

        /* Update poll event after avail list changed */
@@ -682,7 +683,6 @@ int rkmpp_dqbuf(struct rkmpp_context *ctx, struct v4l2_buffer *buffer)

        pthread_mutex_lock(&queue->queue_mutex);
        rkmpp_buffer_clr_available(rkmpp_buffer);
-       TAILQ_REMOVE(&queue->avail_buffers, rkmpp_buffer, entry);
        pthread_mutex_unlock(&queue->queue_mutex);

        rkmpp_buffer_clr_queued(rkmpp_buffer);
```

**Comment by JeffyCN** [comment]
huh, there's indeed a mistake around there, try:
```
--- a/src/libv4l-rkmpp.c
+++ b/src/libv4l-rkmpp.c
@@ -671,9 +671,6 @@ int rkmpp_dqbuf(struct rkmpp_context *ctx, struct v4l2_buffer *buffer)
        rkmpp_buffer = TAILQ_FIRST(&queue->avail_buffers);
        pthread_mutex_unlock(&queue->queue_mutex);

-       /* Update poll event after avail list changed */
-       rkmpp_update_poll_event(ctx);
-
        ret = rkmpp_to_v4l2_buffer(ctx, rkmpp_buffer, buffer);
        if (ret < 0) {
                LOGE("failed to convert buffer\n");
@@ -687,6 +684,9 @@ int rkmpp_dqbuf(struct rkmpp_context *ctx, struct v4l2_buffer *buffer)

        rkmpp_buffer_clr_queued(rkmpp_buffer);

+       /* Update poll event after avail list changed */
+       rkmpp_update_poll_event(ctx);
+
        LOGV(2, "dequeue buffer: %d(%" PRIu64 "), size: %d, type: %d\n",
             buffer->index, rkmpp_buffer->timestamp,
             rkmpp_buffer->bytesused, buffer->type);
```

**Comment by amazingfate** [comment]
Yes that does fix my issue!
