### ISSUE TITLE
[298.737] [RKMPP] [15080] rkmpp_s_fmt(380): ERR: cannot do s_fmt during streaming

### ISSUE THREAD

**Issue by ma-siddiqui** [JeffyCN/libv4l-rkmpp#23]
[298.737] [RKMPP] [15080] rkmpp_s_fmt(380): ERR: cannot do s_fmt during streaming
0:24:58.738 ERROR: Decoder ioctl 3234878981 failed: Device or resource busy

**Comment by JeffyCN** [comment]
this is for chromium only.
