### ISSUE TITLE
An implementation similar to Raspberry Pi's V4L2 for Rockchip.

### ISSUE THREAD

**Issue by ma-siddiqui** [JeffyCN/libv4l-rkmpp#24]
Could you please advise or share a similar implementation of V4L2 for Raspberry Pi on Rockchip using MPP?

**Comment by JeffyCN** [comment]
sorry, i have no idea of that.

i've heard that the upstream has a v4l2 driver and can work with v4l2-request library in ffmpeg, maybe try that?
