### ISSUE TITLE
Segmentation fault in rkmpp_try_fmt

### ISSUE THREAD

**Issue by lvqier** [JeffyCN/libv4l-rkmpp#27]
When rkmpp_try_fmt is called by rkmpp_s_fmt (line 387) for enc, segmentation fault will occur at line 346. Because queue->rkmpp_format may not initialized at that moment.

**Comment by JeffyCN** [comment]
should be fixed now.

**Comment by lvqier** [comment]
I have tested it this afternoon. Segmentation fault was gone. But there's another issue.
rkmpp_reqbufs fails at LINE 454 when input frame format is V4L2_PIX_FMT_YUYV. Because frmsize is not configured for V4L2_PIX_FMT_YUYV, queue->format.plane_fmt[i].sizeimage is always 0.

**Comment by JeffyCN** [comment]
re-uploaded.

you might need to config the other queue first.

**Comment by lvqier** [comment]
Works now! Thanks!
