### ISSUE TITLE
关于libv4l-rkmpp的使用

### ISSUE THREAD

**Issue by fancong5201314** [JeffyCN/libv4l-rkmpp#4]
您好，我这边想使用你的这个libv4l-rkmpp进行H264码流和YUV码流的获取，想看看有没有对应的例子，有几点疑问：
1. 我如何选择是哪个video节点，或者rkisp节点？v4l2直接通过open可以打开指定节点，但是您这个貌似没有；
2. 我想通过select或者poll获取数据，监控的文件句柄是哪个啊？ v4l2直接通过监控open返回的句柄得到的；
3. 如果我想添加HEVC，即H265编码的支持，该如何进行修改啊？
打扰了，谢谢。

**Comment by JeffyCN** [comment]
https://github.com/JeffyCN/libv4l-rkmpp/blob/master/README.md#limitation

**Comment by JeffyCN** [comment]
for chromium only, please read the readme.
