### ISSUE TITLE
v4l2-ctl 通过libv4l-rkmpp抓取h264帧

### ISSUE THREAD

**Issue by linlin4426** [JeffyCN/libv4l-rkmpp#7]
如果我想通过v4l2-ctl命令调佣libv4l-rkmpp直接抓取h264的帧该怎么实现呢？
我尝试了把libv4l-rkmpp编译的libv4l-rkmpp.so放入到/usr/lib/libv4l/plugins/目录，且v4l-utils也打了补丁[0001-libv4l2-Support-mmap-to-libv4l-plugin.patch](https://github.com/JeffyCN/meta-rockchip/blob/release-1.3.0_20200915/recipes-multimedia/v4l2apps/v4l-utils/0001-libv4l2-Support-mmap-to-libv4l-plugin.patch) ，通过v4l2-ctl --list-formats-ext -d /dev/video0 列出支持的格式，似乎还是没有显示出libv4l-rkmpp-enc.c里面添加的H.264、VP8等。

**Comment by JeffyCN** [comment]
please check the readme,
https://github.com/JeffyCN/libv4l-rkmpp/blob/master/README.md

this is for chromium only, cannot work with v4l-ctl
