### ISSUE TITLE
VLC support

### ISSUE THREAD

**Issue by ErikApption** [JeffyCN/libv4l-rkmpp#8]
Thanks for this great repo - any chances you could provide some details to validate VLC configuration with your V4L driver? Is that supported?

**Comment by JeffyCN** [comment]
this is for chromium v4l2 vda only, i don't think it would support vlc.

the major issue here is the output data format, this plugin would only provide yuv420sp(nv12) dma buf.


for vlc, maybe you can try ffmpeg's rkmppdec
