### ISSUE TITLE
rockchip_mpp not found

### ISSUE THREAD

**Issue by neofeo** [JeffyCN/libv4l-rkmpp#9]
Hi sir, well, I installed rockchip_mpp through the repo as "librockchip-mpp" and also compiled it and install it into the system , but for some reason it's not catched by this project. could you give me a hint here? 
librockchip_mpp.so and all the rest are on /usr/local/lib and on /usr/lib they are the one from the repo, it's hard to know why it doesnt pick them.

**Comment by JeffyCN** [comment]
it's using pkg-config to find mpp's .pc file. you can try to use strace to find where the .pc file should be.

**Comment by JeffyCN** [comment]
the pkgconf file should be installed to   /usr/lib/pkgconfig/rockchip_mpp.pc

**Comment by neofeo** [comment]
Ok, closing for now. Thanks!
